export const surveyQuestions = {
  empresa: [
    "¿Compartes los objetivos y las metas que tiene la organización?",
    "¿Te identificas con los valores de la organización?",
    "¿El equipo directivo actúa de forma coherente con la estrategia y los objetivos de la organización?",
    "¿Consideras que hay una buena, clara y precisa comunicación dentro de la empresa?",
    "¿Consideras que en la empresa hay un espíritu de ayuda y colaboración?",
    "¿Me siento comprometido con la Empresa?",
    "¿La Empresa genera instancias de solución ante los problemas?",
    "¿La Empresa brinda planes alternativos de trabajo ante algún problema?",
    "¿Se siente respaldado por la empresa cuando reporta algún inconveniente?",
    "¿La Empresa le brinda espacios de comunicación?",
    "¿Tienes intenciones de desarrollar aún más tu carrera profesional en esta empresa? (Si/No)",
  ],
  jefatura: [
    "¿Comunica de forma clara las prioridades y se asegura de que estas sean entendidas?",
    "¿Les dedica el tiempo necesario a los trabajadores ante cualquier necesidad?",
    "¿Tiene buena disposición para responder todas tus inquietudes?",
    "¿Crees que confía en ti, en tus capacidades y conocimientos para realizar tu trabajo?",
    "¿Ejerce un trato respetuoso hacia los trabajadores?",
    "¿Consideras que tu jefatura trabaja por mantener un buen ambiente de trabajo?",
    "¿Si te llama la atención, lo realiza con justa razón y de manera respetuosa?",
    "¿Encuentras apoyo y confianza en tu jefatura?",
    "¿La toma de decisiones o las órdenes implantadas por su jefatura son justas según su criterio?",
    "¿Si tienes un problema, te facilita apoyo para encontrar la solución?",
    "¿Recibes reconocimientos positivos por parte de tu jefatura?",
  ],
  puesto: [
    "¿Has recibido todas las herramientas, accesos y materiales necesarios para realizar tu trabajo?",
    "¿Qué tan satisfecho estás de tu rol en la Empresa?",
    "¿Conoces el cómo impacta tu trabajo en los objetivos de la empresa?",
    "¿Sientes tener la autonomía suficiente para organizar y realizar tu trabajo?",
    "¿El feedback que recibes de tu jefatura directa sobre tu trabajo te permite mejorar?",
    "¿Las capacitaciones realizadas por la empresa te permiten mejorar tu forma de trabajar?",
    "¿Te sientes valorado en tu puesto de trabajo?",
    "¿Tus opiniones o sugerencias son escuchadas dentro de la empresa?",
    "¿Puedes hacer tu trabajo con normalidad dentro de tu jornada laboral?",
    "¿Requieres recurrentemente tiempo extra para cumplir con tu trabajo?",
    "¿Crees que tu salario está acorde a tus funciones?",
  ],
  equipo: [
    "¿Consideras que hay apoyo y trabajo colaborativo entre compañeros?",
    "¿Consideras que hay un trato respetuoso entre tus compañeros de trabajo?",
    "¿Conoces el trabajo que desempeñan las otras áreas de la empresa?",
    "¿Hay un buen clima laboral en la empresa?",
    "¿Valoras positivamente el ambiente de trabajo?",
    "¿Ayudas a tus compañeros cuando lo necesitan?",
    "¿Si ves a un compañero en problemas, intentas apoyarlo para buscar la solución?",
    "¿Las personas de tu equipo de trabajo aceptan las críticas constructivas de forma positiva?",
    "¿Los objetivos de tu equipo son claros y aceptados por todos?",
    "¿Consideras que tu equipo contribuye en conjunto al cumplimiento de los objetivos?",
    "¿Los miembros del equipo expresan los conflictos de forma abierta y respetuosa buscando la mejor solución?",
  ],
  condiciones: [
    "¿La ventilación en mi área de trabajo es adecuada?",
    "¿La iluminación de mi área de trabajo es adecuada?",
    "¿Las herramientas que utilizo para realizar mi trabajo están en buenas condiciones?",
    "¿Mi espacio de trabajo se encuentra recurrentemente limpio y ordenado?",
    "¿La Empresa se preocupa por mi seguridad personal?",
    "¿La Empresa se preocupa por mantener en buen estado las instalaciones de la Empresa?",
    "¿Me han proporcionado el equipo de seguridad siempre que lo requiero?",
    "¿Me informan recurrentemente los riesgos que existen en la empresa?",
    "¿Los espacios comunes, como baños, oficinas, entre otros, se encuentran siempre limpios y ordenados?",
    "¿Conoce los riesgos y las medidas de prevención relacionadas con su trabajo?",
    "¿Los turnos que tiene la empresa le parecen óptimos?",
  ],
  persona: ["¿Cómo te sientes trabajando con nosotros en la Empresa?"],
  emociones: [
    "Alegría",
    "Gratitud",
    "Motivación",
    "Entusiasmo",
    "Estrés",
    "Malhumorado/a",
    "Ansiedad",
    "Frustración",
    "Disgusto",
  ],
};
